name: Caching 2
on: push


jobs:   
      
<<<<<<< HEAD
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - name: Get npm cache directory
          id: npm-cache-dir
          run: |
            echo "::set-output name=dir::$(npm config get cache)"
        - uses: actions/cache@v3
          id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
            path: ${{ steps.npm-cache-dir.outputs.dir }}
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                    ${{ runner.os }}-node-
            

        - if: ${{ steps.npm-cache-dir.outputs.cache-hit != 'true' }}
          name: List the state of node modules
          continue-on-error: true
          run: npm list

        - name: process run-script
          run: |
              npm install
    
    build2:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - name: Get npm cache directory
          id: npm-cache-dir
          run: |
            echo "::set-output name=dir::$(npm config get cache)"
        - uses: actions/cache@v3
          id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
            path: ${{ steps.npm-cache-dir.outputs.dir }}
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                    ${{ runner.os }}-node-
            

        - if: ${{ steps.npm-cache-dir.outputs.cache-hit != 'true' }}
          name: List the state of node modules
          continue-on-error: true
          run: npm list

        - name: process run-script
          run: |
              npm install
=======
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
                  ${{ runner.os }}-node-
      
      - name: moving files
        run: |
            cp -r node_modules/* /home/runner/work/card-site/card-site/
          
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: npm
     
   
      - name: Install JS dependencies
        if: steps.npm_cache_id.outputs.cache-hit != 'true'
        run: ls package-lock.json && npm install 
   
>>>>>>> 30d5a919b6eb5d4734a545a9a3ea544bd779e823
