name: Caching 2
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
                  ${{ runner.os }}-node-
          

      - if: steps.npm-cache-dir.outputs.cache-hit != 'true' 
        name: install npm
        run: |
            npm install **/package-lock.json --save


      #- name: process run-script
       # run: |
        #     npm install
