name: CI-2

on: 
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: node_modules
        key:  cache-node-module-${{ github.sha)}}
        restore-keys: /
          cache-cache-

    -  run: npm i
    