name: CI-2

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

        
      # with:
        # directory: server # Optional, specify the folder of package-lock.json if not in the root directory

    - name: Install JS dependencies
      run: |
        cd frontend
        npm run build --if-present
    