name: example-rolling-cache
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@HEAD
        with:
          working-directory: card-site
          useRollingCache: true
      - run: npm t
        working-directory: examples/rolling-cache