name: CI-2

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: c-hive/gha-npm-cache@v1
      # with:
        # directory: server # Optional, specify the folder of package-lock.json if not in the root directory

    - name: Install JS dependencies
      run: npm install
    